AWSTemplateFormatVersion: 2010-09-09
Resources:
  HelloworldLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: helloworld
      Handler: index.handler
      Role: arn:aws:iam::1234567890:role/LambdaRole
      Runtime: nodejs8.10
      Timeout: 10
      Code:
        S3Bucket: sample-bucket
        S3Key: helloworld/deploy/lambda.zip
      Tags:
        -
          Key: COST
          Value: helloworld-lambda
  LambdaScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
        Description: 'schedule event for lambda'
        ScheduleExpression: 'cron(0/1 * * * ? *)'
        State: ENABLED
        Targets:
          - Arn: !GetAtt HelloworldLambdaFunction.Arn
            Id: ScheduleEvent1Target
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref HelloworldLambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleEvent.Arn
Outputs:
  StackName:
    Value: !Ref AWS::StackName
  StackID:
    Value: !Ref AWS::StackId